---

- name: create  ~/.ssh/sockets directory
  file:
    path: ~/.ssh/sockets
    state: directory
    mode: 0750

- name: "write ssh config for user {{ user }}"
  template:
    src: "ssh_config.j2"
    dest: "~/.ssh/config"
    owner: "{{ user }}"
    group: staff
    mode: "0644"
  when: ssh_user_config is defined
