---
# add homebrew taps
- community.general.homebrew_tap:
    name: "{{ item }}"
    state: present
  loop: "{{ homebrew_taps }}"

# loop over homebrew_packages
- community.general.homebrew:
    name: "{{ item }}"
    state: present
  loop: "{{ homebrew_packages }}"

# loop over homebrew_casks
- community.general.homebrew_cask:
    name: "{{ item }}"
    state: present
  loop: "{{ homebrew_casks }}"

